apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: buid-push-run
spec:
  taskRef:
    name: docker-image
  resources:
    inputs:
      - name: git-resource
        resourceRef:
          name: git-resource
    outputs:
      - name: image-resource
        resourceRef:
          name: image-resource